src/App.js, src/Components/Main.js, src/Components/MypageDefault.js, src/css/MypageDefault.css
📍Summary
마이페이지-기본화면 구현
📖 Describe your changes
MypageDefault 페이지 생성 및 css 적용하였고,
이를 확인하기 위해 Main.js에서 Link함
🚀 Issue number and link
#9
=> 마이페이지-기본화면 구현

src/App.js, src/Components/CommunityNoti.js, src/Components/NotiBox.js, src/Components/Sidebar.js, src/css/CommunityNoti.module.css, src/css/NotiBox.module.css
커뮤니티 알림 화면 UI 구현
CommunityNoti페이지 생성 및 css 적용하였고, SideBar의 커뮤니티 알림에 링크함.
<ul>
<li>
알림 박스 동적 추가
</li>
<li>
커뮤니티 글과 링크</li>
</ul>
=> [커뮤니티 알림] 구현 및 side bar 연결

package-lock.json, src/App.js, src/Components/CelebBox.js, src/Components/CelebRecommend.js, src/components/MainBar.js, src/css/CelebBox.module.css, src/css/CelebRecommend.module.css
셀럽 추천 화면 UI 구현
CelebRecommend페이지 생성 및 css 적용하였고, MainBar의 추천에 링크함.
<ul>
<li>
팔로우 버튼 활성화
</li>
<li>
셀럽 아이템 동적 추가</li>
</ul>
=> [셀럽추천] 화면 구현 및 mainBar 연결

package-lock.json, src/Components/AccountManage.js, src/css/AccountManage.module.css, src/css/CelebBox.module.css, src/css/CelebRecommend.module.css, src/css/CommunityNoti.module.css, src/css/MypageDefault.module.css, src/css/NotiBox.module.css
반응형 레이아웃 설정
윈도우의 크기를 줄이면 레이아웃이 깨지는 오류가 발생한다는 보고 받았다.
윈도우 크기가 변경되어도 레이아웃 위치가 고정될 수 있도록 각 스타일 코드에 min-width를 1000px로 설정하였다.
=>  [계정관리, 셀럽추천, 커뮤니티알림, 마이페이지기본 화면] 반응형 레이아웃 설정

package-lock.json, package.json, src/Components/Register.js, src/Components/RegisterForm.js, yarn.lock
백엔드와 연결하기 위해 회원가입 페이지의 기능을 구현하였다
* 각 요소(이메일, 비밀번호, 아이디, 생년, 생월, 생일, 성별)의 값 읽기
* 생년, 생월, 생일 하나로 합치기
* 해당 값들을 서버로 보내기
* 결과 console로 확인 
* 실제로 열려있는 서버로 바꾸기
* 비밀번호 확인 과정 추가
* 회원가입 성공 시 로그인 화면으로 link
=> [회원가입] 기능 구현

src/Components/CommunityWrite.js
post로 서버에 데이터를 보냅니다. 
body: { feedId, writerId, content} 
만들고 보니, 제목 칸이 없는 점.. 수정하겠습니다.
또한 body 서버가 아직 없어서 제대로 테스트해보지 못한 점..
=> CommunityWrite 서버에 데이터 전송

src/Components/HomeFeed.js, src/Components/feed.js
feed에 json데이터를 불러옵니다. 
한 피드에 사진을 여러개 업로드 할 수 있으므로, 
일단 ui를 수정한 후 데이터 가져오는 방식을 바꾸도록 하겠습니다.
=> feed 데이터 가져오기

src/Components/Login.js, src/Components/LoginForm.js, src/css/Login.module.css
백엔드와 연결하기 위해 로그인 페이지의 기능을 구현하였다
* 각 요소(이메일, 비밀번호)의 값 읽기
* 해당 값들을 서버로 보내기
* 로그인 성공 시 HomeFeed로 이동
* 로그인 실패 시 alert
* 실제로 열려있는 서버로 바꾸기
=> [로그인] 기능 구현

src/index.js
ReactDOM.render를 createRoot로 바꾸었다.
React 18에서는 더이상 ReactDOM.render를 사용할 수 없어 createRoot로 변경하였다.
=> [버그 수정] index.js 렌더링 버전 변경

src/Components/CommunityFeed.js, src/Components/SlideButton.js, src/Components/comfeed.js, src/css/comfeed.module.css
홈-피드와 동일합니다
- 한 피드에 사진을 여러장 올릴 수도 있으므로, comfeed 컴포넌트에 버튼을 추가하여 다음/이전 사진으로 넘길 수 있는 기능 추가했습니다.
- 사진이 여러 개이므로, comfeed 매개변수 배열로 받았습니다. (현재는 하드코딩 상태)
- 예전엔 무한 스크롤의 스크롤 바를 없애버려서 ,노트북 키패드로만 넘길 수 있었는데,  마우스로도 넘길 수 있도록 버튼을 만들었습니다. (SlideButton파일)
=> 커뮤니티-피드 axios, 피드 버튼, 좌우스크롤 버튼 추가

src/Components/CommunityNoti.js, src/css/CommunityNoti.module.css
백엔드와 연결하기 위해 로그인 페이지의 기능을 구현하였다
* 스크롤 조정
* 전체적인 ui 수정
* 페이지네이션 ui 추가
* 푸터 붙이기
* 페이지네이션 기능 설정
=> [UI] 커뮤니티 알림 - 페이지네이션, 푸터 추가 #56

src/Components/CommunityNoti.js, src/Components/NotiBox.js, src/css/CommunityNoti.module.css, src/css/NotiBox.module.css
커뮤니티 알림 페이지의 기능을 구현하였다.
* 페이지 수, 아이템 수 설정
* 서버 데이터 가져와서 아이템과 연결
* 알림 제목과 커뮤니티 본문 연결
* 실제로 열려있는 서버로 바꾸기
=> [기능 추가] 커뮤니티 알림 - 서버 연결 및 페이지 설정 #61

src/App.js, src/Components/FeedPopup.js, src/Components/HomeFeed.js, src/Components/UserFeed.js, src/css/FeedPopup.module.css
개인 피드 팝업으로 설정, 디자인 변경
추후 사용자 선택시, 해당 팝업으로 넘어가게 변환 필요함!
=> [디자인 변경] 팝업 설정, 디자인 변경 #66

src/Components/CelebBox.js, src/Components/CelebRecommend.js, src/css/CelebBox.module.css, src/css/CelebRecommend.module.css
셀럽추천 페이지의 css를 수정하였다.
* 사이드바 제거
* wrap 스크롤 해제
* margin 변경
*  이미지 크기 변경
* 타이틀 설정
=> [UI] 셀럽추천 - CSS 수정 #71

src/Components/Login.js, src/Components/LoginForm.js, yarn.lock
로그인 페이지의 세 가지 bug를 수정하였다.
* LoginForm.js의 body 태그 삭제
* Login.js의 body 태그 삭제
* NavLink exact 속성 지정, to 속성 변경
=> [BugFix] 로그인 css 오류 해결

src/Components/CelebBox.js, src/Components/CelebRecommend.js, src/css/CelebBox.module.css, src/css/CelebRecommend.module.css
기기에 따라 페이지가 잘려 보이는 상황이 발생해 css를 수정하였다.
* margin 변경
*  이미지 크기 변경
* 타이틀 설정
=> [UI] 셀럽추천 css 수정 #71

src/Components/HomeFeed.js, src/Components/HomeInfo.js, src/Components/ItemInfo.js, src/Components/feed.js
=> [Feat] Axios get

src/Components/CommunityWrite.js, src/Components/HomeFeed.js, src/Components/HomeInfo.js, src/Components/MyPageComments.js, src/Components/MyPageWritings.js, src/Components/WritingBox.js, src/Components/feed.js
홈 화면 Feed들 Get api 연결했습니다.
CommunityWrite 질문 글 post api 연결했습니다.
Item은 아직 api가 안 만들어져서, 임시로 수정했고요, 홈 화면에서 버튼 누르면 정보 post하는 것도 아직 api가 안 만들어져서 임시로 슬기 피드로 대체했습니다~ 
feedUrl을 String으로 post하는 걸로 되어있던데, 나중에 수정 요청해야 할 것 같습니다~
=> CommunityWrite POST Api 연결

src/Components/CommunityWrite.js, src/Components/HomeInfo.js, src/Components/feed.js, src/css/feed.module.css
홈 화면에서 피드를 누르면, 그 피드를 HomeInfo창에 넘겨서, 해당 피드가 뜨도록 수정했습니다.
커뮤니티 글 작성 버튼을 누르면 피드 정보를 CommunityWrite에 전달하여, feedUrl이 수정되도록 수정했습니다. 
이미지 url이 너무 길어 data too long for column 오류가 떴고, 백엔드에서 임시방편으로 column크기를 수정했습니다.
나중에 media_id를 넘기거나..그런 방법으로 효율적으로 바꿀 수 있을 것 같습니다.!
=> 홈 - 피드 정보 넘기기 /  커뮤니티 - 글 작성 post 수정

MypageDefaultForm.js, src/Components/MypageDefault.js, src/Components/MypageDefaultForm.js
마이페이지 기본화면과 백엔드 서버를 연결했다.
* 서버로부터 user, following list 정보 get
* ui로 나타내기
* Like list get
=> Mypage default server connect #85

src/Components/CommunityFeed.js, src/Components/CommunityInfo.js, src/Components/CommunityWrite.js, src/Components/comfeed.js, src/css/CommunityWrite.module.css, src/css/comfeed.module.css, src/css/feed.module.css
**api/post Api** 연결했습니다.
피드 눌러서 뜨는 팝업 close 이벤트 수정했습니다..
CommunityWrite profile내용 **api/user/me** Api 연결해서 가져왔습니다.
=> 커뮤니티 - 피드 GET Api 연결 + 수정

src/Components/AccountManageForm.js, src/Components/MypageDefault.js, src/Components/MypageDefaultForm.js, src/css/MypageDefault.module.css
프로필이 있는 사용자도 기본 이미지로 적용되는 버그 수정, css 수정
* 기본 이미지 적용 안 되는 bug 수정
* css 수정
=> [Bug, UI] 마이페이지 기본 css 수정

src/App.js, src/Components/CommentBox.js, src/Components/MyPageComments.js, src/css/CommentBox.module.css
내가 작성한 댓글 get api 연결했습니다.
삭제 버튼 누르면 삭제하는 api 연결하고, 화면에 삭제 즉시 반영되게 수정했습니다.
+ 댓글 수정 기능은 불필요한 것 같아서 없앴습니다.
+ 날짜 필드 추가 필요합니다..
=> [API] 마이페이지 - 내가 작성한 댓글 api 연결

src/Components/FeedPopup.js, src/Components/HomeFeed.js, src/Components/HomeInfo.js, src/Components/ItemInfo.js, src/Components/UserFeed.js, src/Components/feed.js, src/css/HomeInfo.module.css, src/css/ItemInfo.module.css
=> [feat] Item api 연결

src/hooks/useHomeItemLogic.js, src/hooks/useWritePost.js, src/pages/community/popup/WritePopup.js, src/pages/homeItem/HomeItem.js
질문 글 post 시, 원래 feed url을 전송합니다. (blob 전송안됨)
=> fix: 질문 글 post

public/data/userdata.json, src/App.css, src/Components/MainBar.js, src/Components/SearchBar.js, src/Components/SearchresultItem.js, src/Components/mainHeader/mainBarDefault.js, src/pages/search/Search.js, src/style/style.css
자동검색어 기능 개발했습니다!!!!!
모두 실행시키기 전에
`cd ./public/data`
`json-server --watch userdata.json --port 5000 `
순서대로 입력해서 json server 실행시킨 후, npm start로 작동하면 됩니다!!!
=> Feat/#119 userdata 

src/pages/community/home/Community.js, src/pages/login/Login.js, src/utils/axios.jsx
토큰 만료 시 refresh하는 api 연결했습니다. 
로그인 하면 main 페이지로 이동하게 수정했습니다.
hotfix/token -> `dev`
=> refact: token 만료 처리

src/pages/community/detail/CommunityDetail.js, src/pages/community/detail/comment/Comment.js, src/style/style.css
이유는 모르겠지만 flexColumn한 css가 다 깨져서, 수정했습니다.
=> fix: css 수정

src/pages/community/home/Community.js
pagination api연결하는 것 보다 프론트에서 slice하는게 더 빠를 것 같아서 구현했습니다.
`community`
> - pagination 구현 (한페이지 12장) 
feat/#121-community-pagination-> `dev`
Issue #121
=> feat: community pagination 구현

src/pages/main/Main.js
=> chore: main 수정

.github/workflows/cd.yml, .github/workflows/ci.yml
ubuntu 버전 latest로 변경, nginx 코드 삭제
=> fix: ubuntu version, nginx 삭제
